// Auto-generated by scripts/wasm-refresh.mjs. Do not edit by hand.
// Derived from project(VERSION …) in the repo-root CMakeLists.txt.
export const CADML_VERSION = '0.3';
export const CADML_SOFTWARE_VERSION = '0.3.0';
