// Typed wrapper around the CADML WebAssembly module. The C++ build emits
// a UMD factory + binary which are vendored in git at
// /public/wasm/cadml-{VERSION}.{js,wasm} (regenerated by `pnpm
// wasm:refresh`). In a browser script context the factory is hoisted to
// `window.createCadml`; this file injects the <script>, waits for it to
// load, calls the factory, and caches the resolved module so the WASM is
// fetched + instantiated at most once per page.

'use client';

import { CADML_VERSION } from './cadml-version';

export interface CompileResult {
  ok: boolean;
  fcadml: string;
  errors: string;
  warnings: string;
}

export interface InMemoryFile {
  path: string;
  contents: string;
}

export interface CadmlModule {
  compileSource(src: string): CompileResult;
  exportStlFromSource(src: string): Uint8Array | null;
  export3mfFromSource(src: string): Uint8Array | null;
  compileProject(files: InMemoryFile[], entry: string): CompileResult;
  exportStlFromProject(files: InMemoryFile[], entry: string): Uint8Array | null;
}

interface FactoryOptions {
  locateFile?: (path: string) => string;
  print?: (msg: string) => void;
  printErr?: (msg: string) => void;
}

type Factory = (opts?: FactoryOptions) => Promise<CadmlModule>;

declare global {
  interface Window {
    createCadml?: Factory;
  }
}

const LOADER_URL = `/wasm/cadml-${CADML_VERSION}.js`;
const WASM_URL   = `/wasm/cadml-${CADML_VERSION}.wasm`;

let cached: Promise<CadmlModule> | null = null;

export function loadCadml(): Promise<CadmlModule> {
  if (typeof window === 'undefined') {
    return Promise.reject(
      new Error('loadCadml() may only be called in the browser')
    );
  }
  if (cached) return cached;

  const local = new Promise<CadmlModule>((resolve, reject) => {
    const finish = (factory: Factory) => {
      factory({ locateFile: (p) => p === 'cadml.wasm' ? WASM_URL : `/wasm/${p}` })
        .then(resolve)
        .catch(reject);
    };

    if (window.createCadml) {
      finish(window.createCadml);
      return;
    }

    const existing = document.querySelector<HTMLScriptElement>(
      'script[data-cadml-loader]'
    );
    const script = existing ?? document.createElement('script');
    if (!existing) {
      script.src = LOADER_URL;
      script.async = true;
      script.dataset.cadmlLoader = 'true';
    }
    script.addEventListener('load', () => {
      if (!window.createCadml) {
        reject(new Error('cadml.js loaded but window.createCadml is undefined'));
        return;
      }
      finish(window.createCadml);
    }, { once: true });
    script.addEventListener('error', () => {
      reject(new Error(`Failed to load ${LOADER_URL}`));
    }, { once: true });
    if (!existing) document.head.appendChild(script);
  });

  // If the load fails (network blip, missing artifact, corrupted
  // module), evict the cache so the next caller retries instead of
  // receiving the same rejection forever.
  local.catch(() => {
    if (cached === local) cached = null;
  });
  cached = local;
  return local;
}
