// Rebuild the CADML WebAssembly module from the parent repo and vendor
// the artifacts into web/public/wasm/, version-stamped from the parent
// CMakeLists.txt. The version-stamped filenames (cadml-{version}.{js,
// wasm}) double as cache-bust keys and tell you at a glance which
// release is shipping.
//
// Run this when src/wasm/* or any src/cadml*/* C++ source changes:
//
//   pnpm wasm:refresh
//
// Prereqs (one-time, in the parent repo root, with emsdk_env activated):
//
//   cmake --preset wasm

import { execFileSync }           from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync,
         readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath }          from 'node:url';

const here     = dirname(fileURLToPath(import.meta.url));
const webRoot  = resolve(here, '..');
const repoRoot = resolve(webRoot, '..');
const buildDir = join(repoRoot, 'build', 'wasm');

if (!existsSync(join(buildDir, 'CMakeCache.txt'))) {
  console.error('[wasm:refresh] build/wasm not configured. From the repo root, run:');
  console.error('              cmake --preset wasm');
  console.error('              (needs emsdk activated; first run takes ~10 min)');
  process.exit(1);
}

const VERSION = (() => {
  const cml = readFileSync(join(repoRoot, 'CMakeLists.txt'), 'utf8');
  const m   = cml.match(/project\(\s*cadml[\s\S]*?VERSION\s+(\d+)\.(\d+)\.(\d+)/);
  if (!m) {
    console.error('[wasm:refresh] could not parse VERSION from ../CMakeLists.txt');
    process.exit(1);
  }
  return `${m[1]}.${m[2]}`;
})();

console.log(`[wasm:refresh] cadml ${VERSION} — building C++ -> WASM ...`);
try {
  execFileSync('cmake', ['--build', buildDir], {
    stdio: 'inherit',
    cwd:   repoRoot,
  });
} catch {
  console.error('\n[wasm:refresh] cmake build failed.');
  console.error('              Ensure emsdk is activated in this shell.');
  process.exit(1);
}

const dstDir = join(webRoot, 'public', 'wasm');
mkdirSync(dstDir, { recursive: true });

for (const [src, dst] of [
  ['cadml.js',   `cadml-${VERSION}.js`],
  ['cadml.wasm', `cadml-${VERSION}.wasm`],
]) {
  const from = join(buildDir, src);
  const to   = join(dstDir, dst);
  copyFileSync(from, to);
  const kb = (statSync(to).size / 1024).toFixed(1);
  console.log(`[wasm:refresh] ${src} -> public/wasm/${dst}  (${kb} KB)`);
}

// Single source of truth for the loader — keeps the URL in lib/cadml.ts
// and the artifact filename on disk in lockstep.
writeFileSync(
  join(webRoot, 'lib', 'cadml-version.ts'),
  `// Auto-generated by scripts/wasm-refresh.mjs. Do not edit by hand.\n` +
  `export const CADML_VERSION = '${VERSION}';\n`
);
console.log(`[wasm:refresh] wrote lib/cadml-version.ts`);
